{
 "title": "PGLogical2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": { "query": "select_pglogical_node" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Replication Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(select_pg_replication_slots{host=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(select_pglogical_node{host=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Sets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(select_pglogical_replication_set{host=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(select_pglogical_subscriptions{host=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "WAL Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum_pg_ls_waldir{host=~\"$host\"}",
     "legendFormat": "{{host}} on disk"
    },
    {
     "expr": "select_min_wal_size{host=~\"$host\"}",
     "legendFormat": "{{host}} min"
    },
    {
     "expr": "select_max_wal_size{host=~\"$host\"}",
     "legendFormat": "{{host}} max"
    }
   ]
  },
  {
   "title": "Safe Wal Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "select_pg_replication_slots_wal{host=~\"$host\"}",
     "legendFormat": "db: {{database}} | host: {{host}} | slot_name: {{slot_name}} | LSN restart: {{restart_lsn}}, confirmed: {{confirmed_flush_lsn}} | WAL status: {{wal_status}}"
    }
   ]
  },
  { "title": "Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Slots",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "select_pg_replication_slots{host=~\"$host\"}",
     "legendFormat": "db: {{database}} | host: {{host}} | slot_name: {{slot_name}} | LSN restart: {{restart_lsn}}, confirmed: {{confirmed_flush_lsn}} | WAL status: {{wal_status}}, size: {{safe_wal_size}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "select_pg_stat_replication{host=~\"$host\"}",
     "legendFormat": "LSN sent:{{sent_lsn}} | write:{{write_lsn}} | flush: {{flush_lsn}} | replay:{{replay_lsn}} | database: {{database}} | host: {{host}} | app: {{application_name}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "select_pglogical_node{host=~\"$host\"}",
     "legendFormat": "database: {{database}} | host: {{host}} | node_id: {{node_id}} | node_name={{node_name}}"
    }
   ]
  },
  { "title": "Replication Sets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Inserts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "select_pglogical_replication_set{host=~\"$host\", replicate_insert=\"True\"}",
     "legendFormat": "db: {{database}} | host: {{host}} | SET id: {{set_id}}, name: {{set_name}}, nodeid: {{set_nodeid}}"
    }
   ]
  },
  {
   "title": "Update",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "select_pglogical_replication_set{host=~\"$host\", replicate_update=\"True\"}",
     "legendFormat": "db: {{database}} | host: {{host}} | SET id: {{set_id}}, name: {{set_name}}, nodeid: {{set_nodeid}}"
    }
   ]
  },
  {
   "title": "Delete",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "select_pglogical_replication_set{host=~\"$host\", replicate_delete=\"True\"}",
     "legendFormat": "db: {{database}} | host: {{host}} | SET id: {{set_id}}, name: {{set_name}}, nodeid: {{set_nodeid}}"
    }
   ]
  },
  {
   "title": "Truncate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "select_pglogical_replication_set{host=~\"$host\", replicate_truncate=\"True\"}",
     "legendFormat": "db: {{database}} | host: {{host}} | SET id: {{set_id}}, name: {{set_name}}, nodeid: {{set_nodeid}}"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "select_pglogical_subscriptions{host=~\"$host\"}",
     "legendFormat": "db: {{database}} | host: {{host}} | slot: {{slot_name}}, subscription: {{subscription_name}}, provider_dsn: {{provider_dsn}} origins: {{forward_origins}}, sets: {{replication_sets}}, delay: {{sub_apply_delay}}"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Tables Synchronization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(select_table_replication_status{host=~\"$host\"})",
     "legendFormat": "InSync"
    },
    {
     "expr": "count(select_table_replication_status{host=~\"$host\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Tables Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 66 },
   "targets": [
    {
     "expr": "select_table_replication_status{host=~\"$host\"}",
     "legendFormat": "db: {{database}}, host: {{host}}, table: {{sync_nspname}}.{{sync_relname}}"
    }
   ]
  }
 ]
}